version: "3.1"

services:
    dataBase:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: fastTravelDB
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin 
        volumes:
            - datafiles:/var/lib/mysql
            #prof disse para nao fazer assim, usar uma pasta da nossa home nao no nosso repositorio do projeto
        networks:
            - default
        restart: always

    fasttravelservice:
      depends_on:
        - dataBase
        - messageBroker
      build: ./FastTravelService
      restart: on-failure
      ports:
        - 6868:8000
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://dataBase:3306/fastTravelDB?useSSL=true",
          "spring.datasource.username" : "admin",
          "spring.datasource.password" : "admin",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "server.port": 8000,
          "spring.rabbitmq.username" : "user1",
          "spring.rabbitmq.password" : "user1",
          "spring.rabbitmq.host" : "messageBroker",
          "spring.rabbitmq.port" : 5672
        }'

    messageBroker:
      image: rabbitmq:3.8-management-alpine
      environment:
          - RABBITMQ_DEFAULT_USER=user1
          - RABBITMQ_DEFAULT_PASS=user1
      ports: 
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
        
volumes:
  datafiles: