version: "3.1"

services:
    dataBase:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: fastTravelDB
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin 
        volumes:
            - datafiles:/var/lib/mysql
        networks:
            - default
        restart: always
        healthcheck:
            test: "mysql fastTravelDB -uadmin -padmin -e 'SELECT 1;'"
            interval: 20s
            timeout: 10s
            retries: 2

    fasttravelservice:
      depends_on:
        dataBase:
          condition: service_healthy
        messageBroker:
          condition: service_healthy
      build: ./FastTravelService
      restart: on-failure
      ports:
        - 6868:8000
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://dataBase:3306/fastTravelDB?useSSL=true",
          "spring.datasource.username" : "admin",
          "spring.datasource.password" : "admin",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "server.port": 8000,
          "spring.rabbitmq.username" : "user1",
          "spring.rabbitmq.password" : "user1",
          "spring.rabbitmq.host" : "messageBroker",
          "spring.rabbitmq.port" : 5672
        }'
      healthcheck:
        test: "curl http://localhost:8000"
        interval: 30s
        #interval: 20s
        timeout: 10s
        retries: 3
        #retries: 2

    messageBroker:
      image: rabbitmq:3.8-management-alpine
      environment:
          - RABBITMQ_DEFAULT_USER=user1
          - RABBITMQ_DEFAULT_PASS=user1
      ports: 
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
      healthcheck:
        test: rabbitmq-diagnostics -q status
        interval: 20s
        timeout: 10s
        retries: 2
    
    #generator:
      #build: ./dataGeneratorBroker/
      #restart: on-failure
      #depends_on:
        #dataBase:
         # condition: service_healthy
        #messageBroker:
         # condition: service_healthy
        #fasttravelservice:
       #   condition: service_healthy
      #links:
      #  - messageBroker
    

volumes:
  datafiles: