version: "3.1"

services:
    dataBase:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: fastTravelDB
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin 
        volumes:
            - ./dataBase:/var/lib/mysql
        networks:
            - default
        restart: always

    fasttravel:
      depends_on:
        - dataBase
      build: ./projFastTravelService
      restart: on-failure
      env_file: ./.env
      ports:
        - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true

volumes:
  db: