version: "3.1"

services:
    dataBase:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv=''
        environment:
            MYSQL_DATABASE: fastTravelDB
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin 
        volumes:
            - ./dataBase:/var/lib/mysql
            #prof disse para nao fazer assim, usar uma pasta da nossa home nao no nosso repositorio do projeto
        networks:
            - default
        restart: always

    fasttravelservice:
      depends_on:
        - dataBase
      build: ./FastTravelService
      restart: on-failure
      ports:
        - 6868:8000
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://dataBase:3306/fastTravelDB?useSSL=false",
          "spring.datasource.username" : "admin",
          "spring.datasource.password" : "admin",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "server.port": 8000
        }'

    projFastTravel:
      depends_on:
        - fasttravelservice
      image: nginx
      ports: 
          - "8000:80"
      volumes:
          - ./projFastTravel:/usr/nginx/html/
      links:
          - dataBase
      networks:
          - default
      restart: always  